### ISSUE TITLE
Erroneous dependency

### ISSUE THREAD

**Issue by sveale** [ddavison/kinetic#9]
One of the dependencies listed is 'fs'. This package was unpublished from npmjs.org Fri Jun 13 2014 22:29:28 GMT+0000 (UTC) at the time of this post and should be removed.

**Comment by ddavison** [comment]
is FS part of the core NodeJS package now, meaning that i won't have to include it as a dependency?

**Comment by sveale** [comment]
I don't know, but you shouldn't have to include it as a dependency. Seeing how it's been removed from npmjs.org by the "npm" user I don't really think the repository was ever legit..

**Comment by ddavison** [comment]
`fs-plus` is a package included by atom (http://github.com/atom/fs-plus) would you could change it to that? (and of course update the require statements to be `require 'fs-plus'`  then i'll merge it

**Comment by sveale** [comment]
Yeah I could do that, but it's pointless since the package doesn't use any of the extra functions provided by fs-plus                                                                                                                                                                                                                                          From: DjSent: 15:54 søndag 15. juni 2014To: ddavison/kineticReply To: ddavison/kineticCc: Sverre AleksandersenSubject: Re: [kinetic] Erroneous dependency (#9)fs-plus is a package included by atom (http://github.com/atom/fs-plus) would you could change it to that? (and of course update the require statements to be require 'fs-plus'  then i'll merge it

—Reply to this email directly or view it on GitHub.

**Comment by ddavison** [comment]
hold that thought.. let me just build the project with your branch and see if it works.  if it works, then i'm confident that we don't have to use fs as a dependency

**Comment by ddavison** [comment]
so your `fs` looks just fine.. i can merge that in.  but your change to `getFileContents: ->` is broken :(  the request body is turning up null for me.

**Comment by sveale** [comment]
Ok great. I committed the changes to getFileContents in another commit that I haven't submitted a PR for yet. Could you possibly just merge the FS changes, and then I can submit a PR for the getfilecontents changes later?                                                                                                                                                                                                                                                                          Mvh. Sverre Aleksandersen                                                                                                                                                                                                                                        From: DjSent: 16:07 søndag 15. juni 2014To: ddavison/kineticReply To: ddavison/kineticCc: Sverre AleksandersenSubject: Re: [kinetic] Erroneous dependency (#9)so your fs looks just fine.. i can merge that in.  but your change to getFileContents: -> is broken :(  the request body is turning up null for me.  

—Reply to this email directly or view it on GitHub.

**Comment by ddavison** [comment]
the problem is, you made the changes to the `getFileContents` in the same branch.. 

[see for yourself](https://github.com/ddavison/kinetic/pull/10/files) :smile:

**Comment by sveale** [comment]
Sorry about that! I'm kinda new to github and PRs. Should be fixed now :)
